server:
  port: 9080
  servlet:
    context-path: /client
spring:
  datasource:
    url: jdbc:mysql:///zs_im?serverTimezone=UTC
    password: dream
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  jackson:
    date-format: java.text.SimpleDateFormat
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.im
  mapper-locations: classpath:/mapper/**.xml
