server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///zs_im?serverTimezone=UTC
    password: dream
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.im
  mapper-locations: classpath:/mapper/**.xml
